onboarding = false

[keys]
focus_pane_down = "alt+j"
focus_pane_left = "alt+h"
focus_pane_right = "alt+l"
focus_pane_up = "alt+k"
navigate_pane_down = "down"
navigate_pane_up = "up"
navigate_workspace_down = "j"
navigate_workspace_up = "k"
new_tab = "prefix+c"
next_tab = ["alt+n", "ctrl+alt+]"]
prefix = "ctrl+space"
previous_tab = ["alt+p", "ctrl+alt+["]
reload_config = "prefix+Q"
rename_tab = "prefix+r"
rename_workspace = "prefix+R"
resize_mode = "prefix+]"
split_horizontal = "prefix+minus"
split_vertical = "prefix+|"
switch_tab = "alt+1..9"

[ui]
prompt_new_tab_name = false

[theme]
name = "tokyo-night"
